### ISSUE TITLE
AllOrNone check problem

### ISSUE THREAD

**Issue by kongliangzhong** [Loopring/protocol2#20]
Consider the following test case: 
- Orders:
    - Order 0: sell 10 token A, buy 10 token B, allOrNone == true
    - Order 1: sell 5 token B, buy 5 token A, allOrNone == false
    - Order 2: sell 6 token B, buy 6 token A, allOrNone == true
- Rings:
    - Ring 0: order 0, order 1
    - Ring 1: order 0, order 2

Expected fill amounts of Order 0, 1, 2 should be (10, 10), (4, 4) and (6,6)
Actual result: failed

**Comment by kongliangzhong** [comment]
By swap rings position from [[0, 1], [0, 2]] to [[0, 2], [0, 1]], it works as expected. so maybe we can rely on relay on this.

**Comment by autumn84** [comment]
I  think it is a right result, it should fail. And if we want to success, the position of the two rings should be swapped. Maybe it is better to optimize by relay.

**Comment by kongliangzhong** [comment]
please check test/testExchangeAudit.ts for details.

**Comment by Brechtpd** [comment]
It only failed in the simulator, the smart contracts partially filled order 0 (which of course should not be possible).
Should be fixed in 3db2c64ffad1f95d2df07b933f9d6d70508dc87b.

But I agree, the relay should send the rings in the best order to maximize profits.

**Comment by kongliangzhong** [comment]
Ok, issue closed.
