### ISSUE TITLE
Where is a developer chat?

### ISSUE THREAD

**Issue by jochem-brouwer** [Loopring/protocol2#23]
Is there any channel for developer chat? The telegram seems to be coin-focussed (moonbois) and the discord is not active at all. If I have a question where should I go, or do I have to do it via here?

If there is no developer chat, can one be setup? (On gitter, for example?)

**Comment by Brechtpd** [comment]
Let's use the discord. Like you said, it's not very active for now so I sometimes forget to check it, but it's the correct place. You can mention me so I don't have to check everytime to see if there are new questions for the smart contracts.

**Comment by jochem-brouwer** [comment]
Thank you, if I have a question I will ping you there.
