### ISSUE TITLE
Spendable balance updating in orders with the same owner

### ISSUE THREAD

**Issue by Brechtpd** [Loopring/protocol2#7]
Every order currently has its own spendableS and spendableFee and all owner balances are checked a single time for each order independently before any rings are settled. If, for example, there are 2 different orders with the same owner in 2 different rings and both orders pay fees in LRC, spendableFee will be updated for the first order, but not for the second order, even though they have the same owner. This is a problem because the second order will think it has more LRC available than the owner actually has at that moment, which could make the ERC20 tranfer fail. 

Example in multiple rings: 
Ring 1: [Order X from owner A, Order Y from owner B]
Ring 2: [Order Z from owner C, Order W from owner B]
In this case, if owner B sells the same token, or pay fees in the same token, in Order Y and Order W, the spendable amounts for order W after Ring 1 will not be correct.

I think we should do the following:

#### 1) Orders with the same owner in the same ring
Simply disallow this.

#### 2) Orders with the same owner in different rings
I think this should be possible and we should make sure spendable states are correctly updated without having to query the balance on the ERC20 token every time. Spendable amounts of owners should be shared between orders to make this possible. Owner data should be separated from the order data and each order points to a shared state of the owner.

**Comment by kongliangzhong** [comment]
fixed.
